

CREATE TABLE Tasks(
	[taskid] [int] IDENTITY(1,1) NOT NULL,
	[taskdescription] [nchar](100) NOT NULL,
	[project] [nchar](100) NOT NULL,
	[createdat] [nchar](100) NOT NULL,
	[status] [nchar](100) NOT NULL,
	[email] [nchar](100) NOT NULL,
 CONSTRAINT [PK_Tasks] PRIMARY KEY CLUSTERED 
(
	[taskid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


