export const LOGIN = {
    REQUEST: "LOGIN_USER_REQUEST",
    SUCCESS: "LOGIN_USER_SUCCESS",
    FAIL: "LOGIN_USER_FAIL",
}

export const REGISTER = {
    REQUEST: "REGISTER_USER_REQUEST",
    SUCCESS: "REGISTER_USER_SUCCESS",
    FAIL: "REGISTER_USER_FAIL",
}
export const PROJECT = {
    REQUEST: "CREATE_PROJECT_REQUEST",
    SUCCESS: "CREATE_PROJECT_SUCCESS",
    FAIL: "CREATE_PROJECT_FAIL",
}

export const PROJECTS_GET = {
    REQUEST: "PROJECTS_GET_REQUEST",
    SUCCESS: "PROJECTS_GET_SUCCESS",
    FAIL: "PROJECTS_GET_FAIL",
}

export const PROJECTS_GET_S = {
    REQUEST: "PROJECTS_GET_S_REQUEST",
    SUCCESS: "PROJECTS_GET_S_SUCCESS",
    FAIL: "PROJECTS_GET_S_FAIL",
}

export const USERS_GET = {
    REQUEST: "USERS_GET_REQUEST",
    SUCCESS: "USERS_GET_SUCCESS",
    FAIL: "USERS_GET_FAIL",
}
export const AUSERS_GET = {
    REQUEST: "AUSERS_GET_REQUEST",
    SUCCESS: "AUSERS_GET_SUCCESS",
    FAIL: "AUSERS_GET_FAIL",
}

export const TASK_GET = {
    REQUEST: "PROJECTS_GET_REQUEST",
    SUCCESS: "PROJECTS_GET_SUCCESS",
    FAIL: "PROJECTS_GET_FAIL",
}

export const TASK_GETS = {
    REQUEST: "PROJECTS_GETS_REQUEST",
    SUCCESS: "PROJECTS_GETS_SUCCESS",
    FAIL: "PROJECTS_GETS_FAIL",
}

export const TASK = {
    REQUEST: "CREATE_TASK_REQUEST",
    SUCCESS: "CREATE_TASK_SUCCESS",
    FAIL: "CREATE_TASK_FAIL",
}

export const RESET_NOTIFICATION = "RESET_NOTIFICATION";