export const LOGIN = {
    REQUEST: "LOGIN_USER_REQUEST",
    SUCCESS: "LOGIN_USER_SUCCESS",
    FAIL: "LOGIN_USER_FAIL",
}

export const REGISTER = {
    REQUEST: "REGISTER_USER_REQUEST",
    SUCCESS: "REGISTER_USER_SUCCESS",
    FAIL: "REGISTER_USER_FAIL",
}
export const PROJECT = {
    REQUEST: "CREATE_PROJECT_REQUEST",
    SUCCESS: "CREATE_PROJECT_SUCCESS",
    FAIL: "CREATE_PROJECT_FAIL",
}

export const PROJECTS_GET = {
    REQUEST: "PROJECTS_GET_REQUEST",
    SUCCESS: "PROJECTS_GET_SUCCESS",
    FAIL: "PROJECTS_GET_FAIL",
}

export const TASK_GET = {
    REQUEST: "PROJECTS_GET_REQUEST",
    SUCCESS: "PROJECTS_GET_SUCCESS",
    FAIL: "PROJECTS_GET_FAIL",
}

export const RESET_NOTIFICATION = "RESET_NOTIFICATION";